generate_jokes_task:
  description: >
    Generate 5 Chuck Norris jokes.
  expected_output: >
    A list of Chuck Norris jokes.
  agent: chuck_norris_joke_generator

pick_joke_task:
  description: >
    Pick the best joke from the list.
  expected_output: >
    The best joke from the list of jokes. 
  agent: chuck_norris_joke_picker
